import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SmoothScrolling from "./Compoennts/SmoothScroll";
import StoreContextProvider from "@/Context/StoreContext";
import Footer from "./Compoennts/Footer";
import Navbar from "./Compoennts/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html data-theme='light' lang="en">
      <body className={inter.className}>
        <StoreContextProvider>
          <SmoothScrolling>
            <Navbar />
            {children}
            <Footer />
          </SmoothScrolling>
        </StoreContextProvider>
      </body>
    </html>
  );
}
